### ISSUE TITLE
Organize plot outputs into single html?

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#94] opened 2019-10-30 17:21 UTC
@shahpr 's notes on how to do this:
https://github.com/shahlab/teaching/tree/master/2019-Fall-CompGen/Lab-10

Related to #42

**Comment by FlicAnderson** [comment] 2020-10-07 09:37
Issue #193 is a duplicate of this, but for simplicity, I'm closing THIS copy as there's more information on the other ticket.

**Comment by FlicAnderson** [comment] 2020-10-07 09:38
Also marking this as done (even though #193 is not yet complete, just because it's a copy).

**Closed by FlicAnderson** 2020-10-07 09:37 UTC
Labels: enhancement
