### ISSUE TITLE
Numbers in read_counts.tsv not lining up

### ISSUE THREAD

**Issue by john-s-f** [riboviz/riboviz#250] opened 2021-01-13 16:12 UTC
After examining the read_counts.tsv files from a run of the Gupta and Woolstenhulme datasets, I think something might be wrong with the numbers in them. If you look at these graphs, which have simply graphed the values in those tsv files with no modification, you can see that for the Gupta data, the number of demultiplexed reads (red) and number of reads after contaminant removal (blue) are the same, but the number of contaminants removed (green) is a number, so it should be the case that red bar - green bar = blue bar. Namely, Reads after contaminant removal = demultiplexed reads - contaminants, but it's not.

Similarly, in the Woolstenhulme dataset, the number of reads after adapter removal (red) and number of reads after contaminant removal (blue) are the same but there are contaminants (green). @FlicAnderson suggested that @mikej888 might be the person to ask about this. 
![Screen Shot 2021-01-13 at 11 08 47 AM](https://user-images.githubusercontent.com/37672249/104477948-b6c54d00-558f-11eb-91d9-ba4146717318.png)

**Comment by ewallace** [comment] 2021-01-13 16:24
That looks like a bug.

Best way to check would be a test case fastq.gz with <10 reads in it, some from contaminants, some not. Even 3 reads is enough.

**Comment by mikej888** [comment] 2021-01-13 17:02
This behaviour happens in the vignette also:
```
SampleName	Program	File	NumReads	Description
WTnone	input	/home/ubuntu/riboviz/vignette/input/SRR1042855_s1mi.fastq.gz
963571	input
WTnone	cutadapt	/home/ubuntu/riboviz/vignette/tmp/WTnone/trim.fq
952343	Reads after removal of sequencing library adapters ***
WTnone	hisat2	/home/ubuntu/riboviz/vignette/tmp/WTnone/nonrRNA.fq
467194	rRNA or other contaminating reads removed by alignment to rRNA index files ***
WTnone	hisat2	/home/ubuntu/riboviz/vignette/tmp/WTnone/rRNA_map.sam
952343 Reads with rRNA and other contaminating reads removed by alignment to rRNA index files ***
WTnone	hisat2	/home/ubuntu/riboviz/vignette/tmp/WTnone/unaligned.fq
452996	Unaligned reads removed by alignment of remaining reads to ORFs index files
WTnone	hisat2	/home/ubuntu/riboviz/vignette/tmp/WTnone/orf_map.sam
14516	Reads aligned to ORFs index files
WTnone	riboviz.tools.trim_5p_mismatch	/home/ubuntu/riboviz/vignette/tmp/WTnone/orf_map_clean.sam
14516	Reads after trimming of 5' mismatches and removal of those with more than 2 mismatches

WT3AT	input	/home/ubuntu/riboviz/vignette/input/SRR1042864_s1mi.fastq.gz
1374448	input
WT3AT	cutadapt	/home/ubuntu/riboviz/vignette/tmp/WT3AT/trim.fq
1373362 Reads after removal of sequencing library adapters ***
WT3AT	hisat2	/home/ubuntu/riboviz/vignette/tmp/WT3AT/nonrRNA.fq
486233	rRNA or other contaminating reads removed by alignment to rRNA index files ***
WT3AT	hisat2	/home/ubuntu/riboviz/vignette/tmp/WT3AT/rRNA_map.sam
1373362 Reads with rRNA and other contaminating reads removed by alignment to rRNA index files ***
WT3AT	hisat2	/home/ubuntu/riboviz/vignette/tmp/WT3AT/unaligned.fq
477792	Unaligned reads removed by alignment of remaining reads to ORFs index files
WT3AT	hisat2	/home/ubuntu/riboviz/vignette/tmp/WT3AT/orf_map.sam
8698	Reads aligned to ORFs index files
WT3AT	riboviz.tools.trim_5p_mismatch	/home/ubuntu/riboviz/vignette/tmp/WT3AT/orf_map_clean.sam
8698	Reads after trimming of 5' mismatches and removal of those with more than 2 mismatches
```

The problem is not in `read_counts.tsv`. Inspecting the raw datafiles shows the same effect. For WTnone:

```console
$ echo $(cat trim.fq|wc -l)/4|bc
952343
$ echo $(cat nonrRNA.fq|wc -l)/4|bc
467194
$ samtools view -c rRNA_map.sam 
952343
```
For WT3AT:
```console
$ echo $(cat trim.fq | wc -l)/4 | bc
1373362
$ echo $(cat nonrRNA.fq | wc -l)/4 | bc
486233
$ samtools view -c rRNA_map.sam 
1373362
```

**Comment by ewallace** [comment] 2021-01-13 17:22
This will probably be fixed by adding option `--no-unal` (Suppress SAM records for reads that failed to align) from the [hisat2 manual](https://daehwankimlab.github.io/hisat2/manual/).

Won't that fix then break the regression test for `rRNA_map.sam`, so that needs to be updated?

**Comment by mikej888** [comment] 2021-01-13 17:23
It would indeed break the regression test, for that file but also for `read_counts.tsv`.

**Comment by ewallace** [comment] 2021-01-17 15:36
Could be attacked alongside #267, as both involve hisat2 options.

**Comment by ewallace** [comment] 2021-01-17 17:57
I added`--no-unal` to `process hisat2rRNA` in branch `rrna-nounal-250`.

Vignette ran with different numbers only for `rRNA_map.sam` counts.

```
SampleName	Program	File	NumReads	Description
WTnone	input	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/input/SRR1042855_s1mi.fastq.gz	963571	input
WTnone	cutadapt	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/trim.fq	952343	Reads after removal of sequencing library adapters
WTnone	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/nonrRNA.fq	467194	rRNA or other contaminating reads removed by alignment to rRNA index files
WTnone	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/rRNA_map.sam	485149	Reads with rRNA and other contaminating reads removed by alignment to rRNA index files
WTnone	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/unaligned.fq	452996	Unaligned reads removed by alignment of remaining reads to ORFs index files
WTnone	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/orf_map.sam	14516	Reads aligned to ORFs index files
WTnone	riboviz.tools.trim_5p_mismatch	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WTnone/orf_map_clean.sam	14516	Reads after trimming of 5' mismatches and removal of those with more than 2 mismatches
WT3AT	input	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/input/SRR1042864_s1mi.fastq.gz	1374448	input
WT3AT	cutadapt	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/trim.fq	1373362	Reads after removal of sequencing library adapters
WT3AT	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/nonrRNA.fq	486233	rRNA or other contaminating reads removed by alignment to rRNA index files
WT3AT	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/rRNA_map.sam	887129	Reads with rRNA and other contaminating reads removed by alignment to rRNA index files
WT3AT	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/unaligned.fq	477792	Unaligned reads removed by alignment of remaining reads to ORFs index files
WT3AT	hisat2	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/orf_map.sam	8698	Reads aligned to ORFs index files
WT3AT	riboviz.tools.trim_5p_mismatch	/exports/eddie3_homes_local/ewallac2/riboviz/riboviz/vignette/tmp/WT3AT/orf_map_clean.sam	8698	Reads after trimming of 5' mismatches and removal of those with more than 2 mismatches
```

Check counts of `rRNA_map.sam + nonrrna.fq = trim.fq`:
* WTnone `467194 + 485149 = 952343`
* WT3AT `486233 + 887129 =1373362`

The read counts for all  other steps are the same, and the regression test passed.

Putting in pull request now.

**Comment by ewallace** [comment] 2021-01-18 09:45
I just realized that we also do not need to keep unaligned reads in the `hisat2ORF` step. They take up space and don't do anything. So shouldn't we add `--no-unal` there, too? Related to #267.

**Closed** 2021-01-20 17:05 UTC
Labels: bug, hackathon-2021-01
