### ISSUE TITLE
Issue with 3-nucleotide periodicity plots

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#243] opened 2021-01-12 11:58 UTC
My mouse run once again encountered an error, this time during the generation of the 3-nt periodicity figure. The code was breaking during the call to function `GetGeneDatamatrix5start ` at gene [ENSMUST00000204521](https://useast.ensembl.org/Mus_musculus/Gene/Summary?g=ENSMUSG00000107588;r=6:48589610-48613250;t=ENSMUST00000204521), which has a protein-coding sequence that is only 21-nt (!) long. The issue appears to because the value of variable `nnt_gene` is set to a default value of 50. This variable determines how many nucleotides into the gene (relative to the 5'-end) to include in plot. Because this gene is so short, adding 50 to the start of the 5'-end actually causes an indexing issue. Here is the relevant unaltered block of code

```
GetGeneDatamatrix5start <- function(gene, dataset, hd_file, 
                                    posn_5start, n_buffer, nnt_gene) {
  data_mat_all <- GetGeneDatamatrix(gene, dataset, hd_file)
  # @ewallace: replace this by gff_df?
  # n_utr5 <- BiocGenerics::width(gff[gff$type == "UTR5" & gff$Name == gene])
  
  # if n_buffer bigger than length n_utr5, pad with zeros:
  if (posn_5start > n_buffer) {
    # if posn_5start bigger than n_buffer
    n_left5 <- posn_5start - n_buffer # column to start from (5'end)
    zeropad5_mat <- matrix(0, nrow = nrow(data_mat_all), ncol = 0)
  } else {
    # if length n_utr5 less than n_buffer
    n_left5 <- 1 # column to start from (5'end)
    zeropad5_mat <- matrix(
      0, 
      nrow = nrow(data_mat_all), 
      ncol = (n_buffer - posn_5start + 1 )
    )
  }
  n_right3 <- posn_5start + nnt_gene - 1 # column to end with (3'end), issue is with this line of code

  data_mat_5start <- data_mat_all[, n_left5:n_right3]
  return(cbind(zeropad5_mat, data_mat_5start))
}
```
I think the best solution is to simply include the 3'-end of the gene as an argument to the function and check if `n_right3 <= posn_3end`. If it is, keep as is, else, set `n_right3 = posn_3end`. Alternatively, we might just remove these genes from the plot by using a tryCatch block and returning `NA` if the error occurs and then filter these from the list, but I'd rather not throw out data.

**Comment by ewallace** [comment] 2021-01-12 12:19
Good catch! I like your proposed solution with `posn_3end` as a parameter. Can we give it a default value of `Inf` or something so as not to break existing code?

In the ideal world, we would turn this bug into a unit test for `GetGeneDatamatrix5start`, then code until we passed the test. We don't have the R code in a testing framework yet, but the input and output could still help with that. What do you think?

**Comment by FlicAnderson** [comment] 2021-01-12 17:17
As a larger documentation/testing issue, do you (@acope3 and @ewallace) think it is possible/feasible to do some kind of early check in the `.GFF` file  to look at all gene CDS lengths to find whether our default parameters like `nnt_gene` are likely to cause problems?  This would definitely be a new issue though.

**Comment by ewallace** [comment] 2021-01-12 22:03
@FlicAnderson - yes it's feasible. I don't know if that is better than catching them individually or working around problem genes @acope3 suggests.

Ideally we should leave some log message about which genes were included or excluded. That's already something we're sloppy about, for example in config parameter `count_threshold` (remove genes with a read count below this threshold, when generating statistics and figures). It would make sense to log the lists of included/excluded genes somewhere. Definitely a separate issue ticket.

**Comment by ewallace** [comment] 2021-01-14 13:43
Hi, it looks like this branch was merged into master, which we don't want. How should we fix?

**Comment by acope3** [comment] 2021-01-14 13:46
That's not what it's showing on my end. I see a new branch  [3nt_periodicity_small_orf_issue_243_acope3](https://github.com/riboviz/riboviz/tree/3nt_periodicity_small_orf_issue_243_acope3) with master unmodified.

**Comment by kavousan** [comment] 2021-01-15 17:16
Positive that it passes the regression tests and looks correct.

To test this we would need small datasets with known outcome to see that we arrive at the expected outcome. @Acope to create the ticket and work on it.

**Closed by kavousan** 2021-01-15 17:16 UTC
Labels: hackathon-2021-01

**Comment by ewallace** [comment] 2021-01-15 17:18
My suggestion is to use this bug to create  a unit test for `GetGeneDatamatrix5start()` - new issue ticket.

**Comment by ewallace** [comment] 2021-01-15 17:19
Sorry, is this fix merged to develop?
