### ISSUE TITLE
Make pdf output optional

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#317] opened 2021-05-13 13:43 UTC
Since we now have html output of plots (#193 / #297), we don't need to have the separate pdf outputs by default.

Should we either:
* deprecate/remove pdf outputs entirely?
* create a new parameter `output_pdfs` (or something), default value `FALSE` and only optionally output?

That would require

**Comment by john-s-f** [comment] 2021-05-13 13:50
I wouldn't remove it entirely, people might want PDFs or PNGs to put in powerpoint slides or something. Alternatively, @p6t and I (@john-s-f) should look into adding a [download button](https://shiny.rstudio.com/reference/shiny/latest/downloadButton.html) to the Shiny server, allowing users to download plots from it.

**Comment by mikej888** [comment] 2021-05-18 10:35
Does the HTML output print to PDF from a browser in a nice way (i.e. to a quality comparable to the PDFs output at present) If so I'd say lose the PDF.

Also, consider whether putting the HTML through `wkhtmltopdf` (https://wkhtmltopdf.org/) would yield acceptable PDFs. If so then there would no longer be a need to maintain custom PDF creation code in our R/RMarkdown scripts.

**Comment by ewallace** [comment] 2021-05-26 18:12
I like @john-s-f's suggestion of "download" button as a longer-term solution.

I also think that the custom pdf creation code is lightweight so not a big maintenance problem. It basically goes
* make the plot (1 line, that we need for the html output anyway)
* write to pdf with `ggsave`. 

So it should only be a half hour's work to introduce a parameter `pdf_output`, `output_pdfs`, or `print_pdfs` (votes?) to `generate_stats_figs.R`, then wrap all the plot code chunks in `if` clauses.

**Comment by mikej888** [comment] 2021-05-27 08:23
> So it should only be a half hour's work to introduce a parameter pdf_output, output_pdfs, or print_pdfs (votes?) to generate_stats_figs.R, then wrap all the plot code chunks in if clauses.

Nearer an hour. A guide for adding dependencies is in `upgrade-config-313 branch`, in https://github.com/riboviz/riboviz/blob/upgrade-config-313/docs/developer/dependencies.md. Before adding the parameter to the `upgrade_config.py` tool wait until this branch has been merged.

**Comment by ewallace** [comment] 2021-06-15 13:28
@FlicAnderson and I discussed.

It is easy to add the parameter in R to wrap all the pdf output. However, it is more trouble to update all the tests and so on to not check the pdf output, unsure if possible by Friday.

We can address most of this issue without updating the tests by:
* create a branch from (as @mikej888 recommends) `upgrade-config-313`
* within that branch, add flag to `generate_stats_figs.R` controlling the figure/pdf output
* add a configuration parameter to nextflow config file to control that
* check that tests run with the flag set to true, and keep that as default for vignette and test runs
* postpone decisions about testing with flag set to false until later

**Comment by mikej888** [comment] 2021-06-15 13:42
> create a branch from (as @mikej888 recommends) upgrade-config-313

I'd merged this into `develop` yesterday. The updated links for adding dependencies and configuration are:

* https://github.com/riboviz/riboviz/blob/develop/docs/developer/dependencies.md
* https://github.com/riboviz/riboviz/blob/develop/docs/developer/config.md

**Comment by FlicAnderson** [comment] 2021-06-16 10:58
@mikej888 quick question: in the developer config docs, it advises adding the new parameter to files within `riboviz/test/config/simdata_umi_config_current.yaml` and `riboviz/test/config/simdata_multiplex_config_current.yaml`. 

I can't see these files at those locations in `develop` branch, only `riboviz/test/config/vignette_config_current.yaml` and `vignette_config_1.0.0.yaml`, `vignette_config_1.1.0.yaml` and `vignette_config_2.0.0.yaml`.  

A quick search doesn't reveal them elsewhere either, and they're not visible in `develop` on github: https://github.com/riboviz/riboviz/tree/develop/riboviz/test/config 

Do you have these locally but not tracked/pushed perhaps?

**Comment by mikej888** [comment] 2021-06-16 11:02
@FlicAnderson Sorry, they are indeed gone, I mustn't've updated config.md when I removed them.

**Comment by FlicAnderson** [comment] 2021-06-16 11:03
@mikej888 cheers! Thanks for confirming they're gone :ghost:

**Comment by FlicAnderson** [comment] 2021-06-16 11:06
@mikej888 shall I update that config.md document in my current branch `output_pdfs` (will push in a sec, very new branch, beginning to add new `output_pdfs` parameter to the config file & proliferate through the rest of the files), or should that doc fix be done in `develop` separately?

**Comment by mikej888** [comment] 2021-06-16 11:07
@FlicAnderson I've just done it :-)

**Comment by FlicAnderson** [comment] 2021-06-16 12:56
I've now pushed my initial work on `pdf-optional-317` branch (last commit 9ba17e8963),
This includes: 
* new config parameter `output_pdfs` added to yamls and proliferated through the codebase (EXCLUDING TESTING CODE) as per [docs/developer/config.md](https://github.com/riboviz/riboviz/blob/develop/docs/developer/config.md)
* pdf-related code in generate_stats_figs.R in conditional blocks dependent on `output_pdfs` parameter
* nextflow process generateStatsFigs edited to pass through the output_pdfs config parameter to generateStatsFigs.R.

As it stands, pdfs are generated when output_pdfs is true (current default!), and not generated when it's false. 

I have 2 questions for @mikej888 : 

1) I've used `optional true` (as per https://www.nextflow.io/docs/latest/process.html#optional-output) in prep_riboviz.nf generateStatsFigs process for the pdf outputs.  I don't think this is quite correct, although it works, because it doesn't relate the presence/absence of these pdfs to the params.output_pdfs directly within the nextflow code?  However, this params.output_pdfs IS fed into generateStatsFigs, and the output of pdfs or not does depend on it, so it's happening related to that parameter anyway.  Can you advise on whether this is how you'd handle this in the nextflow code?

2) Can you suggest how to ensure the testing for pdfs only runs with 'output_pdfs = true'?  Aiming for this (as described [here](https://github.com/riboviz/riboviz/issues/317#issuecomment-861497727)):
> check that tests run with the flag set to true, and keep that as default for vignette and test runs   

It'd involve editing `test_generate_stats_figs_pdf`  in `riboviz/test/regression/test_regression.py` presumably, but since I've still got slight holiday brain and we're heading up to release time, if you have any time to help on getting this testing code right I'd be grateful!

**Comment by mikej888** [comment] 2021-06-16 13:10
> 1. I've used optional true (as per https://www.nextflow.io/docs/latest/process.html#optional-output) in prep_riboviz.nf generateStatsFigs process for the pdf outputs. I don't think this is quite correct, although it works, because it doesn't relate the presence/absence of these pdfs to the params.output_pdfs directly within the nextflow code? However, this params.output_pdfs IS fed into generateStatsFigs, and the output of pdfs or not does depend on it, so it's happening related to that parameter anyway. Can you advise on whether this is how you'd handle this in the nextflow code?

@FlicAnderson Some PDF outputs are already dependent upon conditions e.g. `features.pdf` which depends on `is_features_file` (before your change):
 
```
tuple val(sample_id), file("features.pdf") \
    optional (! is_features_file) into features_pdf
```
So instead of :
```  
tuple val(sample_id), file("features.pdf") \
    optional (! is_features_file) optional true into features_pdf<!--EndFragment-->
```
update the condition to also factor in the `output_pdfs` flag e.g.:
```
tuple val(sample_id), file("features.pdf") \
    optional (! (is_features_file && output_pdfs)) into features_pdf
```
i.e. `optional` is FALSE (and `features.pdf` is expected to be output) only if `is_features_file` is TRUE and `output_pdfs` is TRUE.

You might want to manually test this with `output_pdfs` both TRUE and FALSE.

**Comment by FlicAnderson** [comment] 2021-06-16 13:14
Great, thanks! I wasn't sure how the multiple optionals would play together, and how I had it it didn't seem like the best way of doing it.  I'll give that a go.

**Comment by FlicAnderson** [comment] 2021-06-16 14:37
Followed @mikej888's suggestions re: Q2 and the testing code. 

Latest efforts at commit cf1f6a89eb480 on branch `pdf-optional-317`. 

Running the (integration!) tests gives skips for all the PDFs when `output_pdfs` is set to FALSE in vignette/vignette_config.yaml, which is ideal. It does run the tests as expected if output_pdfs is true (also good). 

NOTE: I'm running it here on an old test set which includes the new `.tsv`s from the #193 work, which is why those tests don't show up as skipped (which they do if I use an old regression set without those .tsvs from back in January).

Tests run With PDFs:
```
# output_pdfs TRUE:
(riboviz) fanders6@ceres:~/riboviz/riboviz$ pytest -vs riboviz/test/regression/test_regression.py --expected=$HOME/regression-test-data-20210408-rmarkdown-outputs-193
========================================== test session starts ==========================================
platform linux -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/fanders6/miniconda3/envs/riboviz/bin/python
cachedir: .pytest_cache
rootdir: /home/fanders6/riboviz/riboviz
plugins: cov-2.10.1
collected 96 items                                                                                      

riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-1] Working directory:
/home/fanders6/riboviz/riboviz
N E X T F L O W  ~  version 20.07.1
Launching `/home/fanders6/riboviz/riboviz/prep_riboviz.nf` [distracted_pasteur] - revision: a876a6f500
samples_dir: .
organisms_dir: .
data_dir: .
No such sample file (NotHere): example_missing_file.fastq.gz
[cf/4c419f] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[0e/0e39d8] Submitted process > cutAdapters (WT3AT)
#  ... standard processes happening nicely...
[21/8885f5] Submitted process > bamToH5 (WT3AT)
[6e/ae892c] Submitted process > generateStatsFigs (WTnone)
[e8/ac6f37] Submitted process > generateStatsFigs (WT3AT)
Finished processing sample: WTnone
[d9/d48de8] Submitted process > renameTpms (WTnone)
[b7/4ea811] Submitted process > staticHTML (WTnone)
Finished processing sample: WT3AT
[32/4d4d2d] Submitted process > renameTpms (WT3AT)
[8c/551b26] Submitted process > staticHTML (WT3AT)
[7c/4ef3c3] Submitted process > collateTpms (WTnone, WT3AT)
[1c/ce7e25] Submitted process > countReads
Finished visualising sample: WTnone
Finished visualising sample: WT3AT
Workflow finished! (OK)
SKIPPED
riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-2] SKIPPED
riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-3] SKIPPED
# ... bunch of tests
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-pos_sp_rpf_norm_reads.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-read_lengths.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-3ntframe_bygene.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-3ntframe_bygene_filtered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-sequence_features.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-gene_position_length_counts_5start.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-codon_ribodens_gathered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-tpms.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-3nt_periodicity.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-codon_ribodens.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-features.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-pos_sp_rpf_norm_reads.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-read_lengths.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-startcodon_ribogridbar.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-startcodon_ribogrid.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WTnone-3ntframe_propbygene.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-3nt_periodicity.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-codon_ribodens.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-features.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-pos_sp_rpf_norm_reads.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-read_lengths.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-startcodon_ribogridbar.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-startcodon_ribogrid.pdf] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-True-WT3AT-3ntframe_propbygene.pdf] PASSED
riboviz/test/regression/test_regression.py::test_analysis_outputs_html[vignette/output-WTnone-{}_output_report.html] PASSED
riboviz/test/regression/test_regression.py::test_analysis_outputs_html[vignette/output-WT3AT-{}_output_report.html] PASSED
riboviz/test/regression/test_regression.py::test_collate_tpms_tsv[vignette/output] PASSED
riboviz/test/regression/test_regression.py::test_read_counts_tsv[vignette/output] PASSED

=========================================== warnings summary ============================================
/home/fanders6/miniconda3/envs/riboviz/lib/python3.7/site-packages/Bio/Alphabet/__init__.py:27
  /home/fanders6/miniconda3/envs/riboviz/lib/python3.7/site-packages/Bio/Alphabet/__init__.py:27: PendingDeprecationWarning: We intend to remove or replace Bio.Alphabet in 2020, ideally avoid using it explicitly in your code. Please get in touch if you will be adversely affected by this. https://github.com/biopython/biopython/issues/2046
    PendingDeprecationWarning,
-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 50 passed, 46 skipped, 1 warning in 110.11s (0:01:50) =========================
# pdfs tested as expected, and passing! :D
``` 

And without PDFs: 
```
# output_pdfs FALSE: 
========================= 50 passed, 46 skipped, 1 warning in 110.11s (0:01:50) =========================
(riboviz) fanders6@ceres:~/riboviz/riboviz$ pytest -vs riboviz/test/regression/test_regression.py --expected=$HOME/regression-test-data-20210408-rmarkdown-outputs-193
========================================== test session starts ==========================================
platform linux -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/fanders6/miniconda3/envs/riboviz/bin/python
cachedir: .pytest_cache
rootdir: /home/fanders6/riboviz/riboviz
plugins: cov-2.10.1
collected 96 items                                                                                      

riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-1] Working directory:
/home/fanders6/riboviz/riboviz
N E X T F L O W  ~  version 20.07.1
Launching `/home/fanders6/riboviz/riboviz/prep_riboviz.nf` [sharp_ekeblad] - revision: a876a6f500
samples_dir: .
organisms_dir: .
data_dir: .
No such sample file (NotHere): example_missing_file.fastq.gz
[7f/334903] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[93/2aab5c] Submitted process > cutAdapters (WT3AT)
[7b/e9c931] Submitted process > cutAdapters (WTnone)
# ... standard good old riboviz things ....
[a7/46f07d] Submitted process > makeBedgraphs (WTnone)
[65/7a98c6] Submitted process > bamToH5 (WTnone)
[c6/8e0bd2] Submitted process > hisat2ORF (WT3AT)
[31/b55445] Submitted process > trim5pMismatches (WT3AT)
[53/d925a0] Submitted process > samViewSort (WT3AT)
[18/725e34] Submitted process > outputBams (WT3AT)
[2f/914b7d] Submitted process > bamToH5 (WT3AT)
[04/49c065] Submitted process > makeBedgraphs (WT3AT)
[01/9d6264] Submitted process > generateStatsFigs (WTnone)
[01/854c91] Submitted process > generateStatsFigs (WT3AT)
Finished processing sample: WTnone
[c2/5de353] Submitted process > renameTpms (WTnone)
[ec/cbed8f] Submitted process > staticHTML (WTnone)
Finished processing sample: WT3AT
[81/4b2df3] Submitted process > renameTpms (WT3AT)
[35/a9bf67] Submitted process > staticHTML (WT3AT)
[f4/dd016c] Submitted process > collateTpms (WTnone, WT3AT)
[ed/afa97c] Submitted process > countReads
Finished visualising sample: WTnone
Finished visualising sample: WT3AT
Workflow finished! (OK)
SKIPPED
riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-2] SKIPPED
riboviz/test/regression/test_regression.py::test_hisat2_build_index[YAL_CDS_w_250-vignette/index-3] SKIPPED
# ... bunch of tests doing fine ... 
riboviz/test/regression/test_regression.py::test_bam_to_h5_h5[vignette/output-WT3AT] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-3nt_periodicity.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-codon_ribodens.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-pos_sp_nt_freq.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-pos_sp_rpf_norm_reads.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-read_lengths.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-3ntframe_bygene.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-3ntframe_bygene_filtered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-sequence_features.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-gene_position_length_counts_5start.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-codon_ribodens_gathered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WTnone-tpms.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-3nt_periodicity.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-codon_ribodens.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-pos_sp_nt_freq.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-pos_sp_rpf_norm_reads.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-read_lengths.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-3ntframe_bygene.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-3ntframe_bygene_filtered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-sequence_features.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-gene_position_length_counts_5start.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-codon_ribodens_gathered.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_tsv[vignette/output-WT3AT-tpms.tsv] PASSED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-3nt_periodicity.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-codon_ribodens.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-features.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-pos_sp_rpf_norm_reads.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-read_lengths.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-startcodon_ribogridbar.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-startcodon_ribogrid.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WTnone-3ntframe_propbygene.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-3nt_periodicity.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-codon_ribodens.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-features.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-pos_sp_rpf_norm_reads.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-read_lengths.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-startcodon_ribogridbar.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-startcodon_ribogrid.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_generate_stats_figs_pdf[vignette/output-False-WT3AT-3ntframe_propbygene.pdf] SKIPPED
riboviz/test/regression/test_regression.py::test_analysis_outputs_html[vignette/output-WTnone-{}_output_report.html] PASSED
riboviz/test/regression/test_regression.py::test_analysis_outputs_html[vignette/output-WT3AT-{}_output_report.html] PASSED
riboviz/test/regression/test_regression.py::test_collate_tpms_tsv[vignette/output] PASSED
riboviz/test/regression/test_regression.py::test_read_counts_tsv[vignette/output] PASSED

=========================================== warnings summary ============================================
/home/fanders6/miniconda3/envs/riboviz/lib/python3.7/site-packages/Bio/Alphabet/__init__.py:27
  /home/fanders6/miniconda3/envs/riboviz/lib/python3.7/site-packages/Bio/Alphabet/__init__.py:27: PendingDeprecationWarning: We intend to remove or replace Bio.Alphabet in 2020, ideally avoid using it explicitly in your code. Please get in touch if you will be adversely affected by this. https://github.com/biopython/biopython/issues/2046
    PendingDeprecationWarning,
-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 34 passed, 62 skipped, 1 warning in 116.55s (0:01:56) =========================
# PDF tests skipped, as they aren't there :)

``` 
Seems to be working as expected!

**Comment by FlicAnderson** [comment] 2021-06-16 14:39
Merged in latest develop as of f22e32d8

**Comment by FlicAnderson** [comment] 2021-06-16 14:47
Created pull request #367 to close this issue, making pdf output optional (although by default it is set to TRUE currently).

Next steps: (for new issue ticket!) consider making `output_pdfs` default value FALSE, probably after Release 2.1, to be in R2.2? 
This would be good to discuss at Dev meeting @ewallace @mikej888 etc?

**Comment by FlicAnderson** [comment] 2021-06-16 15:48
Mike has fixed the last tweak to this, it's merged into `develop` and closing!

**Closed by FlicAnderson** 2021-06-16 15:48 UTC
Labels: R2.1, R2.2
