### ISSUE TITLE
Issue with running HISAT 2.2 example from vignette

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#188] opened 2020-06-10 20:43 UTC
Hello,

I attempted to run the example described in the vignette. However, it appears to run into an issue when mapping reads to the yeast rRNA sequences using HISAT2. I'm attaching one of the log files. From what I can tell, it is breaking because HISAT2 is expecting a minimum read length of 20. I'm using HISAT2 v.2.2.0.
[02_hisat2_rrna.log](https://github.com/riboviz/riboviz/files/4761093/02_hisat2_rrna.log)

**Comment by ewallace** [comment] 2020-06-17 15:53
Hi Alex,
Thanks for filing the issue. That's a strange observation, because although it's logical, this is not a problem we've had before. The vignette works for several of us on several computers and we haven't had this hisat2 fail.

@acope3 what version of cutadapt are you using?
@FlicAnderson what version of hisat2 works for you?

Edward

**Comment by mikej888** [comment] 2020-06-17 16:01
My version of hisat2 is hisat2-2.1.0.

@acope3, please add the number of lines and size of the file ` vignette/tmp/WTnone/trim.fq`:

```console
$ wc -l  vignette/tmp/WTnone/trim.fq 
$ du -sb vignette/tmp/WTnone/trim.fq 
```

**Comment by FlicAnderson** [comment] 2020-06-17 16:05
Hi @acope3  - Same as @mikej888 , I'm using hisat2-2.1.0, but I'm happy to investigate further if you're able to provide more info as Mike recommended - I'll be able to compare your logs with mine and see if we can figure out where the error is coming from.  It's not something I've seen before either, but thanks for bringing it up!

**Comment by ewallace** [comment] 2020-06-30 20:28
Request that @acope3 updates us if this still needs help, otherwise we'll close the issue.

**Comment by acope3** [comment] 2020-06-30 20:40
Apologies, I've been in the middle of finishing up my dissertation, so this got lost in the shuffle. Based on the attached file, I'm using cutadapt 2.10 with Python 3.6.8.
[01_cutadapt.log](https://github.com/riboviz/riboviz/files/4854296/01_cutadapt.log)


> My version of hisat2 is hisat2-2.1.0.
> 
> @acope3, please add the number of lines and size of the file ` vignette/tmp/WTnone/trim.fq`:
> 
> ```
> $ wc -l  vignette/tmp/WTnone/trim.fq 
> $ du -sb vignette/tmp/WTnone/trim.fq 
> ```
> 
> Also, please attach the content of `vignette/logs/<DATE>/WTnone/WTnone_01_cutadapt.log`

These two commands 3809372 and 106710847, respectively.

**Comment by mikej888** [comment] 2020-07-01 09:11
A `diff` between `01_cutadapt.log` (renamed to `cutadapt_orig.log`) from a release 2.0-beta tag regression test run against @acope3's log:

```console
$ diff 01_cutadapt.orig.log 01_cutadapt.log
1c1
< This is cutadapt 1.18 with Python 3.7.3
---
> This is cutadapt 2.10 with Python 3.6.8
3,4c3,4
< Processing reads on 4 cores in single-end mode ...
< Finished in 3.67 s (4 us/read; 15.76 M reads/minute).
---
> Processing reads on 8 cores in single-end mode ...
> Finished in 3.44 s (4 us/read; 16.82 M reads/minute).
10d9
< Reads that were too short:              11,228 (1.2%)
18c17
< Sequence: CTGTAGGCACC; Type: regular 3'; Length: 11; Trimmed: 958926 times.
---
> Sequence: CTGTAGGCACC; Type: regular 3'; Length: 11; Trimmed: 958926 times
24,26c23,25
<   A: 29.0%
<   C: 17.8%
<   G: 29.8%
---
>   A: 29.1%
>   C: 17.9%
>   G: 29.9%
28c27
<   none/other: 1.1%
---
>   none/other: 0.9%
83d81
<
```

File sizes from the regression test run are identical to those provided by Alex:

```console
$ wc -l vignette-20200304-2.0.beta/vignette-20200304-2.0.beta/tmp/WTnone/trim.fq
3809372 vignette-20200304-2.0.beta/vignette-20200304-2.0.beta/tmp/WTnone/trim.fq
$ du -sb vignette-20200304-2.0.beta/vignette-20200304-2.0.beta/tmp/WTnone/trim.fq
106710847       vignette-20200304-2.0.beta/vignette-20200304-2.0.beta/tmp/WTnone/trim.fq
```

**Comment by mikej888** [comment] 2020-07-01 09:19
On EDDIE cutadapt 2.10 was used (this run used the Nextflow implementation of the RiboViz workflow which is why the log file is named differently and is within `work` but it uses the same `cutadapt` command-line invocation):

```console
$ diff work/01/08e517f2c93d669077d4c493eb73f5/.command.log 01_cutadapt.log
1,4c1,4
< This is cutadapt 2.10 with Python 3.7.6
< Command line parameters: --trim-n -O 1 -m 5 -a CTGTAGGCACC -o trim.fq SRR1042855_s1mi.fastq.gz -j 0
< Processing reads on 1 core in single-end mode ...
< Finished in 13.98 s (15 us/read; 4.14 M reads/minute).
---
> This is cutadapt 2.10 with Python 3.6.8
> Command line parameters: --trim-n -O 1 -m 5 -a CTGTAGGCACC -o vignette/tmp/WTnone/trim.fq vignette/input/SRR1042855_s1mi.fastq.gz -j 0
> Processing reads on 8 cores in single-end mode ...
> Finished in 3.44 s (4 us/read; 16.82 M reads/minute).
23,27c23,27
<   A: 29.2%
<   C: 18.0%
<   G: 30.1%
<   T: 22.3%
<   none/other: 0.4%
---
>   A: 29.1%
>   C: 17.9%
>   G: 29.9%
>   T: 22.2%
>   none/other: 0.9%

$ wc -l work/01/08e517f2c93d669077d4c493eb73f5/trim.fq
3809372 work/01/08e517f2c93d669077d4c493eb73f5/trim.fq
$ du -sb work/01/08e517f2c93d669077d4c493eb73f5/trim.fq
106710847       work/01/08e517f2c93d669077d4c493eb73f5/trim.fq
```
Again, identical file sizes.

**Comment by mikej888** [comment] 2020-07-01 09:31
My `02_hisat2_rrna.log` is:

```
/home/ubuntu/hisat2-2.1.0/hisat2-align-s version 2.1.0
64-bit
Built on login-node03
Wed Jun  7 15:53:42 EDT 2017
Compiler: gcc version 4.8.2 (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
952343 reads; of these:
  952343 (100.00%) were unpaired; of these:
    467194 (49.06%) aligned 0 times
    485149 (50.94%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
50.94% overall alignment rate
```

**Comment by mikej888** [comment] 2020-07-01 10:07
Alex is using HISAT 2.2.0. HISAT 2.2.0 is not listed at ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads. Googling revealed http://daehwankimlab.github.io/hisat2/ which announced the HISAT 2.2.0 release 2/6/2020 available via http://daehwankimlab.github.io/hisat2/download/. So I used the new release:

```console
$ wget -O hisat2-2.2.0-Linux_x86_64.zip https://cloud.biohpc.swmed.edu/index.php/s/hisat2-220-Linux_x86_64/download
$ unzip hisat2-2.2.0-Linux_x86_64.zip
$ export PATH=~/hisat2-2.2.0:$PATH
$ hisat2 --version
/home/ubuntu/hisat2-2.2.0/hisat2-align-s version 2.2.0
64-bit
Built on parkch-desktop
Thu Feb  6 15:10:16 CST 2020
Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY -std=c++11
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```
After running (again via the Nextflow version of RiboViz):
```console
$ nextflow run /home/ubuntu/riboviz/prep_riboviz.nf -params-file vignette/vignette_config.yaml -ansi-log false
```
Unlike Alex's attempt, the run completes and `hisat2` runs fine. But the log data is different to that from HISAT2 2.1.0:
```console
$ cat work/2c/aa5ec51591efa4535f01624ad658f7/.command.log
/home/ubuntu/hisat2-2.2.0/hisat2-align-s version 2.2.0
64-bit
Built on parkch-desktop
Thu Feb  6 15:10:16 CST 2020
Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY -std=c++11
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
  File "/home/ubuntu/hisat2-2.2.0/hisat2_read_statistics.py", line 182
    length_map = sorted(length_map.iteritems(), key=lambda (k,v):(v,k), reverse=True)
                                                           ^
SyntaxError: invalid syntax
952343 reads; of these:
  952343 (100.00%) were unpaired; of these:
    466472 (48.98%) aligned 0 times                # formerly 467194 (49.06%) aligned 0 times
    485871 (51.02%) aligned exactly 1 time     # formerly 485149 (50.94%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
51.02% overall alignment rate
```
Numerous regression tests fail starting with the outputs from `hisat2`:
```console
$ pytest -vs riboviz/test/regression/test_regression.py --expected=vignette-nextflow --nextflow --check-index-tmp --skip-workflow

riboviz/test/regression/test_regression.py::test_hisat_fq[vignette/tmp-WTnone-nonrRNA.fq] FAILED
riboviz/test/regression/test_regression.py::test_hisat_fq[vignette/tmp-WTnone-unaligned.fq] FAILED
riboviz/test/regression/test_regression.py::test_hisat_fq[vignette/tmp-WT3AT-nonrRNA.fq] FAILED
riboviz/test/regression/test_regression.py::test_hisat_fq[vignette/tmp-WT3AT-unaligned.fq] FAILED
riboviz/test/regression/test_regression.py::test_hisat2_sam[vignette/tmp-WTnone-orf_map.sam] FAILED
riboviz/test/regression/test_regression.py::test_hisat2_sam[vignette/tmp-WTnone-rRNA_map.sam] FAILED
riboviz/test/regression/test_regression.py::test_hisat2_sam[vignette/tmp-WT3AT-orf_map.sam] FAILED
riboviz/test/regression/test_regression.py::test_hisat2_sam[vignette/tmp-WT3AT-rRNA_map.sam] FAILED
...
```

**Comment by mikej888** [comment] 2020-07-01 10:09
To summarise - 4 issues:

1. Alex's issue `--read-lengths arg must be at least 20` and the failure of `hisat2`.
2. Why Alex gets this issue and we don't
3. `SyntaxError: invalid syntax` error in the log.
4. Different outputs from `hisat2` 2.1.0 vs. 2.2.0.

**Comment by mikej888** [comment] 2020-07-01 10:11
For 1. Alex's issue --read-lengths arg must be at least 20 and the failure of hisat2:


```
--read-lengths arg must be at least 20
```

a user asked about this on https://www.biostars.org/p/432115/ and then followed up with:

> I does seem some sequences in my fastq(s) were not minimum length. I will have to filter for length before running. Problem solved. Thanks for your reply.

Another user commented that:

> I also got this error with hisat2 v2.2.0 but v2.1.0 works fine. Must be a recent change...?

**Comment by mikej888** [comment] 2020-07-01 10:12
For 3. `SyntaxError: invalid syntax error` in the log a user asked about this on https://www.biostars.org/p/435194/. The response was:

> Yeah, this seems to be a problem related to python3 whereas the script expects python2.

They specified Python 2 and then got:

```
Use of uninitialized value $read_len_str in string ne at ./hisat2 line 293.
```

To me this is not a good solution. Python 2 is end-of-life!

**Comment by mikej888** [comment] 2020-07-01 10:25
2. Why Alex gets this issue and we don't

This is unclear.

**Comment by mikej888** [comment] 2020-07-01 10:31
4. Different outputs from hisat2 2.1.0 vs. 2.2.0.

This is unclear. https://github.com/DaehwanKimLab/hisat2/releases/tag/v2.2.0 documents the key changes to functionality.

A quick inspection of the TPMS_collated.tsv file shows minor changes in certain values:

If HISAT 2.1.0 is used:

```
ORF	WTnone	WT3AT
YAL001C	116.7	953
YAL002W	212.8	365.8
YAL003W	199013.8	100458.6
YAL005C	249986.3	239069
YAL007C	6223	3821.5
...
```

If HISAT 2.1.2 is used:

```
ORF	WTnone	WT3AT
YAL001C	116.7	952.6
YAL002W	212.8	365.7
YAL003W	199005.8	100409.3
YAL005C	249976.2	238951.6
YAL007C	6222.7	3819.6
...
```
A decision needs to be made whether the differences in these, and other outputs, are acceptable.

**Comment by mikej888** [comment] 2020-07-01 10:31
Personally issue 1. and 3. would make me wary of using HISAT 2.2.0 until it is more stable and that we should recommend users continue with HISAT 2.1.0 for now.

**Comment by acope3** [comment] 2020-07-01 13:53
Thank you, @mikej888. Perhaps it is worth noting that I run into the same issue with HISAT 2.2.0 when running it independently of RiboViz. I can install HISAT 2.1.0 to see if that fixes things on my end.

**Comment by acope3** [comment] 2020-12-14 19:31
I ran riboviz on our lab's server with hisat2 v2.2.0 and did not encounter the error I originally posted. Unlike last time, I also ran riboviz within a conda environment. I reran riboviz outside of a conda environment on the computer I was using when I first generated the error and encountered the same issue with hisat2 v2.2.0.

**Comment by ewallace** [comment] 2021-01-19 18:35
I propose that we close this issue as it isn't causing any problems.

**Comment by acope3** [comment] 2021-02-03 16:15
I agree.

**Closed** 2021-02-03 16:37 UTC
Labels: bug
